---
- name: Install docker
  package:
    name: docker.io
    state: present

- name: install python wrapper for docker
  package:
    name: python-docker
    state: present

- name: Install JAVA
  package:
    name: default-jre
    state: present

- name: run jenkins container
  docker_container:
    name: jenkins
    image: jenkins/jenkins
    state: started
    ports:
     - "127.0.0.1:8080:8080"
     - "127.0.0.1:50000:50000"

- name: wait until netowrk socket responds
  pause:
    seconds: 30

- name: get Jenkins CLI
  get_url:
    url: http://localhost:8080/jnlpJars/jenkins-cli.jar
    dest: /root/jenkins-cli.jar

- name: provide job template
  copy:
    src: config.xml
    dest: /root/config.xml

- name: retrieve admn password
  shell: docker exec jenkins cat /var/jenkins_home/secrets/initialAdminPassword
  register: jenkinssecret

- name: Create jenkins job
  shell: cat /root/config.xml | java -jar /root/jenkins-cli.jar -s http://localhost:8080 -auth admin:{{ jenkinssecret.stdout }} create-job lasttestbuild

- name: Copy service definition
  copy:
    src: build.service
    dest: /etc/systemd/system/

- name: Copy build service script
  copy:
    src: build.sh
    dest: /root/build.sh

- name: start and enable build service
  systemd:
    name: build
    state: started
    enabled: yes
